(defpackage #:l-math
  (:use :common-lisp)
  (:nicknames :lm)
  (:export #:*equivalence-tolerance*
	   #:copy
	   #:vector
	   #:make-vector
	   #:to-vector
	   #:copy-vector
	   #:vector=
	   #:do-each-vector-element
	   #:length
	   #:norm
	   #:normalise
	   #:normalise!
	   #:dot-product
	   #:angle-between
	   #:euclidean-distance
	   #:cross-product
	   #:elt
	   #:x
	   #:y
	   #:z
	   #:w
	   #:matrix
	   #:matrix-rows
	   #:matrix-cols
	   #:make-matrix
	   #:matrix-elt
	   #:make-identity
	   #:do-each-matrix-element
	   #:do-each-matrix-element-2
	   #:test-dimensions
	   #:c+
	   #:c-
	   #:negate
	   #:transpose
	   #:negate!
	   #:c*
	   #:c/
	   #:*
	   #:/
	   #:-
	   #:+
	   #:yaw-matrix
	   #:pitch-matrix
	   #:roll-matrix
	   #:create-rotation-matrix
	   #:create-rotation-from-view
	   #:create-rotation-from-view-to-view
	   #:to-degrees
	   #:to-radians
	   #:l-math-error
	   #:dimension-error
	   #:zero-length-error
	   #:linear-interpolation
	   #:between)
  (:shadow #:vector
	   #:make-vector
	   #:length
	   #:elt
	   #:*
	   #:/
	   #:-
	   #:+))
